name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

defaults:
  run:
    working-directory: auth

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - run: npm install

      - run: npm run build

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::881990811866:role/Github-Actions
          aws-region: us-east-1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/auth/latest/remoteEntry.js"
